name: Rakuten Check

on:
  workflow_dispatch:
  schedule:
    # 夜間 1:00～6:00 JST → UTC 16:00～21:00（1時間ごと）
    - cron: '0 16-21 * * *'
    # 日中 7:00～23:45 JST → UTC 22:00～14:45（15分ごと）
    - cron: '0,15,30,45 22-23,0-14 * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Rakuten Check
        env:
          LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
          LINE_USER_ID: ${{ secrets.LINE_USER_ID }}
        run: python rakuten_check.py
