name: Rakuten Check

on:
  workflow_dispatch:   # 手動実行用
  schedule:
    - cron: '0 * * * *'   # 毎時0分に実行（UTCなので注意）

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          pip install requests
      - name: Run Rakuten Check
        run: |
          python rakuten_check.py
