name: Rakuten Check

on:
  workflow_dispatch:
  schedule:
    # 夜1時～朝6時は1時間ごと
    - cron: '0 1-6 * * *'
    # その他の時間は15分ごと
    - cron: '*/15 0,7-23 * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Rakuten Check
        env:
          LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
          LINE_USER_ID: ${{ secrets.LINE_USER_ID }}
        run: python rakuten_check.py
