name: Rakuten Check

on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install selenium
          pip install line-bot-sdk

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: latest

      - name: Setup ChromeDriver
        uses: actions/setup-chromedriver@v1
        with:
          version: latest  # 最新安定版を自動取得

      - name: Run Rakuten Check
        env:
          LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
          LINE_USER_ID: ${{ secrets.LINE_USER_ID }}
        run: python rakuten_check.py
