name: Rakuten Check

on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install selenium
          pip install line-bot-sdk

      - name: Install ChromeDriver
        run: |
          # ランナーにインストール済みChromeのバージョンを確認
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}')
          echo "Chrome version: $CHROME_VERSION"
          # ChromeDriver バージョンは Chrome のメジャーバージョンに合わせる（例: 118.0.5993.90）
          wget -N https://chromedriver.storage.googleapis.com/118.0.5993.90/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          chmod +x chromedriver
          sudo mv chromedriver /usr/local/bin/

      - name: Run Rakuten Check
        env:
          LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
          LINE_USER_ID: ${{ secrets.LINE_USER_ID }}
        run: python rakuten_check.py
