name: Rakuten Check

on:
  workflow_dispatch:
  schedule:
    # 夜1時～6時 JST → UTC 16:00～21:00
    - cron: '0 16-21 * * *'
    # その他の時間は15分ごと（0:00、7:00～23:45 JST） → UTCに変換
    # UTC 15:00（0:00 JST）と 22:00～14:45（7:00～23:45 JST）
    - cron: '0,15,30,45 15,22,23,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14 * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Rakuten Check
        env:
          LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
          LINE_USER_ID: ${{ secrets.LINE_USER_ID }}
        run: python rakuten_check.py
